new generator is ready
SAMdesk/graphql-codegen-node pull request #1
Opened 2019-06-03 21:35 UTC by AnkushSharma2698

2019-06-03 22:39 UTC, ssolbak requested changes
Missing init method?

https://github.com/SAMdesk/samdesk.io/blob/event_page_to_display_gql_clients/src/events/host/graphql_clients/geo_service_client.js#L16

2019-06-04 20:02 UTC, trevonromanuik approved these changes

2019-06-04 20:02 UTC, trevonromanuik commented on codegen.js
> +          output+= generate_helpers(c);
formatting

2019-06-04 20:02 UTC, trevonromanuik commented on codegen.js
> +              console.log("File path: ", file_path);
remove this

2019-06-04 20:03 UTC, merged